export const authTypes = {
  FETCH_AUTH_USER_START: 'FETCH_AUTH_USER_START',
  FETCH_AUTH_USER_SUCCESS: 'FETCH_AUTH_USER_SUCCESS',

  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',

  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',

  SIGN_OUT: 'SIGN_OUT',
};
