export const appActionTypes = {
  FETCH_REMOTE_CONFIG: 'FETCH_REMOTE_CONFIG',
  FETCH_REMOTE_CONFIG_ERROR: 'FETCH_REMOTE_CONFIG_ERROR',
  FETCH_REMOTE_CONFIG_SUCCESS: 'FETCH_REMOTE_CONFIG_SUCCESS',
};
